### ISSUE TITLE
Review code for unix time issues

### ISSUE THREAD

**Issue by jspayne** [benja810/redball#5]
There was [a case](https://github.com/benja810/redball/blob/5be8d68e8585d80a9514a83cf9d92f67ba404508/bots/lemmy_mlb_game_threads/__init__.py#L2484) when checking how long to update the post-game thread where it was trying to interpret the post submitted time coming back from Lemmy as unix time, when Lemmy returns a time string.

Check the code for other instances of time coming from lemmy being treated as a number.

**Comment by benja810** [comment]
Closed by #6
